name: David Wirthlin
favicon: null
layout_spectrum: 0.49711
typography_spectrum: 1
title: DavidWirthlin.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9a9a7'
    - '#33383b'
    - '#d94f28'
    - '#717171'
    - '#98462e'
  brandStrength: 0
  lightness: 0.12905046623200178
  saturation: 0.6952467430382967
  rhythmicContrast: 0.1442911154590547
purpose: []
