name: David Wirthlin
favicon: null
layout_spectrum: 0.06639264686964452
typography_spectrum: 0.75042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14361529471352696
  lightness: 0.12905046623200178
  saturation: 0.6952467430382967
  rhythmicContrast: 0.1442911154590547
purpose: []
